# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbfff75a0f35bb31b3f692b2737d33a658039b8d07c082aef2c4f31b1d6d2951c40a507192fbaad0f7e555e3fc366d5a122efabc4c0e45a731bf311cc6bf61fe

test:
  secret_key_base: be8ec8d0f570c40393ad03396c64f113c14739e35676b6a03e9155e7725088ef52bd5f8a632e28fc5d14daa5c3291e6c9598cd8ba7d2b141b7cb0b27b7e03ab3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
